author: Savi
name: pull-from-base
description: >
  A GitHub Action to automatically create pull requests
  from a changing upstream base repository.
inputs:
  github-token:
    description: User token to be associated with this pull request.
    required: true
  github-username:
    description: >
      The username associated with the given `github-token`.
      If the standard `secrets.GITHUB_TOKEN` is used, then this input
      can be omitted, causing it to use the standard `GITHUB_ACTOR` env var.
    required: false
  source-repo:
    description: Repo to pull from (e.g. `savi-lang/base-repo-library`)
    required: true
  source-branch:
    description: Branch to pull from (e.g. `main`)
    required: true
  target-repo:
    description: Repo to pull into (e.g. the current repository)
    required: true
  target-branch:
    description: Branch to pull into (e.g. `main`)
    required: true
  pull-request-title:
    description: Title of the new pull request to be created
    required: false
  pull-request-body:
    description: Body of the new pull request to be created
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
